### ISSUE TITLE
convert java2typescript-jackson to standalone project

### ISSUE THREAD

**Issue by atsu85** [atsu85/java2typescript-jackson#1]
Currently [raphaeljolivet/java2typescript](https://github.com/raphaeljolivet/java2typescript) project [isn't actively maintained any more, except](https://github.com/raphaeljolivet/java2typescript/graphs/contributors) the [java2typescript-jackson](https://github.com/raphaeljolivet/java2typescript/tree/master/java2typescript-jackson) module, where I've done almost all the recent changes.

As I'm only interested in maintaining java2typescript-jackson module, this issue should convert it to top-level project, to allow it to evolve faster (build tool, versions of JDK and dependency libraries, version of the project itself, including versioning strategy) without considering other subprojects of [raphaeljolivet/java2typescript](https://github.com/raphaeljolivet/java2typescript).

Big thanks to @raphaeljolivet, for creating that project, but at the moment I feel, I might be able to move faster without other subprojects.

**Comment by raphaeljolivet** [comment]
Thanks for having taking care of that project.
I follow it from distance.
