### ISSUE TITLE
Support for String enums

### ISSUE THREAD

**Issue by HarlesPilter** [atsu85/java2typescript-jackson#26]
Since Typescript 2.4 we have support for String enums, would be nice if java2typescript would support them. Generate something like:

```typescript 
export enum Colors {
    Red = 'Red',
    Green = 'Green',
    Blue = 'Blue',
}
```

**Comment by atsu85** [comment]
Couple of hints to implement it:
* You could create new custom enum format writer class (perhaps call it `EnumTypeToStringValuedEnumWriter`) based on `EnumTypeToEnumPatternWriter`.
* There are convenience methods that replace default enum writer with custom writer - create one for new format as well.
* Write test for the writer: take a look at WriterPreferencesTest.enumToEnumPattern
* To test it within another application locally, build and deploy it to local maven repo using `gradlew publishToMavenLocal`

**Comment by atsu85** [comment]
@HarlesPilter, please try it out and confirm it meets your expectations as well
